# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uJ6TM1aAmkdBJs3vGB2_jqASaMJo0aZ
"""

!pip install transformers datasets accelerate evaluate scikit-learn -q

import numpy as np
import pandas as pd
import torch

from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)

from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.utils.class_weight import compute_class_weight

dataset = load_dataset("go_emotions")

train_df = pd.DataFrame(dataset["train"])
val_df = pd.DataFrame(dataset["validation"])
test_df = pd.DataFrame(dataset["test"])

train_df["label"] = train_df["labels"].apply(lambda x: x[0] if len(x) > 0 else None)
val_df["label"] = val_df["labels"].apply(lambda x: x[0] if len(x) > 0 else None)
test_df["label"] = test_df["labels"].apply(lambda x: x[0] if len(x) > 0 else None)

train_df = train_df.dropna()
val_df = val_df.dropna()
test_df = test_df.dropna()

emotion_map = {
    17:0,  # joy
    18:1,  # love
    2:2,   # anger
    25:3,  # sadness
    14:4,  # fear
    27:5,  # surprise
    8:6,   # curiosity
    16:7   # gratitude
}

train_df = train_df[train_df["label"].isin(emotion_map.keys())]
val_df = val_df[val_df["label"].isin(emotion_map.keys())]
test_df = test_df[test_df["label"].isin(emotion_map.keys())]

train_df["label"] = train_df["label"].map(emotion_map)
val_df["label"] = val_df["label"].map(emotion_map)
test_df["label"] = test_df["label"].map(emotion_map)

num_classes = len(emotion_map)
class_weights_array = np.ones(num_classes) # Initialize with default weight 1.0 for all classes

# Compute weights only for the classes present in train_df["label"]
unique_labels_in_train = np.unique(train_df["label"])

if len(unique_labels_in_train) > 0: # Ensure there's at least one label to compute weights for
    weights_for_present_classes = compute_class_weight(
        class_weight="balanced",
        classes=unique_labels_in_train,
        y=train_df["label"]
    )
    # Map these computed weights back to the full 8-element array
    for label, weight in zip(unique_labels_in_train, weights_for_present_classes):
        if label < num_classes: # Ensure label is within expected range 0-7
            class_weights_array[label] = weight

class_weights = torch.tensor(class_weights_array, dtype=torch.float)

tokenizer = AutoTokenizer.from_pretrained("roberta-base")

train_encodings = tokenizer(
    train_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    val_df["text"].tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

train_dataset = Dataset.from_dict(train_encodings)
train_dataset = train_dataset.add_column("labels", train_df["label"].tolist())

val_dataset = Dataset.from_dict(val_encodings)
val_dataset = val_dataset.add_column("labels", val_df["label"].tolist())

model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels=8
)

import torch.nn as nn

class WeightedTrainer(Trainer):

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):

        labels = inputs.get("labels")

        outputs = model(**inputs)

        logits = outputs.get("logits")

        loss_fct = nn.CrossEntropyLoss(weight=class_weights.to(model.device))

        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="macro"
    )

    acc = accuracy_score(labels, predictions)

    return {
        "accuracy": acc,
        "f1_macro": f1,
        "precision_macro": precision,
        "recall_macro": recall
    }

training_args = TrainingArguments(

    output_dir="./emotion_model",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,

    num_train_epochs=6,

    weight_decay=0.01,

    load_best_model_at_end=True,

    metric_for_best_model="f1_macro",

    fp16=True
)

trainer = WeightedTrainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=val_dataset,

    compute_metrics=compute_metrics,

    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()

trainer.train()

trainer.evaluate()

model.save_pretrained("emotion_transformer_model")
tokenizer.save_pretrained("emotion_transformer_model")

from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="emotion_transformer_model",
    tokenizer="emotion_transformer_model"
)

classifier("I am extremely grateful for your help today!")